### ISSUE TITLE
Ollama and Xeon 5660

### ISSUE THREAD

**Issue by Andreh1982** [jmorganca/ollama#1435] opened 2023-12-08 15:57 UTC
Hello! I'm facing an issue running Ollama in a Dell T610 server with 64GB ram and Xeon 5660:

`Dec  8 15:52:15 constellation kernel: [ 1529.028302] traps: ollama-runner[2213] trap invalid opcode ip:472d79 sp:7ffdbe33f680 error:0 in ollama-runner[407000+da000]
Dec  8 15:52:15 constellation ollama[2161]: 2023/12/08 15:52:15 llama.go:436: signal: illegal instruction (core dumped)`

Please, any help in this situation? The processor is too old to run llm models? :(

**Comment by easp** [comment] 2023-12-08 21:17
Ollama is compiled to use the AVX instruction set instructions. That CPU was released well over a decade ago and doesn't support AVX.
https://ark.intel.com/content/www/us/en/ark/products/47921/intel-xeon-processor-x5660-12m-cache-2-80-ghz-6-40-gt-s-intel-qpi.html

There has been some talk about relaxing that requirement, but for now your only option (besides different hardware) is downloading the repo, changing compile options, and compiling your own version. I believe that all the compile options that need to be changed are in this file: /llm/llama.cpp/generate_linux.go

**Comment by technovangelist** [comment] 2023-12-08 21:18
I think it is a bit old. That was released in 2010 and AVX instructions started showing up in 2011. And since there is no mention on the Intel page about the 5660, I think it may be missing that critical component, and maybe others.

**Comment by Cybervet** [comment] 2023-12-09 18:12
Just recompiled the repo and I can confirm that runs fine in CPUs without AVX. Running it in a proxmox LXC debian container. 
Only thing I did was set AVX=off to /llm/llama.cpp/generate_linux.go

**Comment by Andreh1982** [comment] 2023-12-09 19:54
Thank you so much, guys! Got success here, disabling AVX direct on llama.cpp also did the trick. Cheers! :)

**Comment by Andreh1982** [comment] 2023-12-09 20:03
Oh by the way, i made it on llama.cpp based on the messages on this issue, thank you!

> Just recompiled the repo and I can confirm that runs fine in CPUs without AVX. Running it in a proxmox LXC debian container. Only thing I did was set AVX=off to /llm/llama.cpp/generate_linux.go

did you get any performance issues?

**Comment by Cybervet** [comment] 2023-12-09 20:47
Its a bit slow, but that is expected , 2.5 -5 (Orca2) tokens/sec with 4 cores assigned to the container. I am trying now to pass through the GPU to see if it will make a difference.

**Comment by Andreh1982** [comment] 2023-12-09 20:58
> Its a bit slow, but that is expected , 2.5 -5 (Orca2) tokens/sec with 4 cores assigned to the container. I am trying now to pass through the GPU to see if it will make a difference.

here the first run is really slow, but after that, goes fine i guess. I will try later to emulate the flag using a custom cpu in proxmox. Not having AVX instructions is a problem, many other services need it like mongodb for example...

**Comment by Cybervet** [comment] 2023-12-09 21:11
Yeap I know , I just have a couple of workstations with dual cpus around and I thought to try them out.

**Comment by Andreh1982** [comment] 2023-12-09 21:45
I just bought one past week... haha, didnt expected this kind of problem :(

**Closed** 2023-12-13 23:24 UTC
