### ISSUE TITLE
Enabling langchain

### ISSUE THREAD

**Issue by suoko** [jmorganca/ollama#748] opened 2023-10-10 14:13 UTC
I found this video about implementing langchain with ollama. If available it should be easy to use it via ollama-ui

https://www.youtube.com/watch?v=CPgp8MhmGVY

**Comment by technovangelist** [comment] 2023-10-11 13:17
hey, that’s my video about langchain and ollama. ollama-ui is a community project not created by us. Not sure what the issue is.

**Comment by jmorganca** [comment] 2023-10-11 15:45
Hi @suoko as @technovangelist mentioned ollama-ui isn't maintained in this repo, but you can check it out here https://github.com/ollama-ui/ollama-ui

I'll close this for now but feel free to re-open if you there's an issue with Ollama. There are also some langchain eaxmples in this repo: https://github.com/jmorganca/ollama/tree/main/examples

**Closed by jmorganca** 2023-10-11 15:45 UTC
