### ISSUE TITLE
invalid version

### ISSUE THREAD

**Issue by UICJohn** [jmorganca/ollama#887] opened 2023-10-24 01:32 UTC
Hi guys
I am tring to build model from Modelfile by following this [guid](https://github.com/jmorganca/ollama/blob/main/docs/import.md).It works fine until I am tring to create from Modelfile using this command:
`ollama create 7b-32k-instruct -f ./Modelfile`
Here is my Modelfile:
```
FROM ./q4_0.bin
TEMPLATE "[INST] {{ .Prompt }} [/INST]"
```
It returns:
`⠋ creating model layer  Error: invalid version`

**Comment by jmorganca** [comment] 2023-10-24 01:40
Hi @UICJohn , may I ask which model you're looking to import?

**Comment by UICJohn** [comment] 2023-10-24 03:02
@jmorganca I was tring to import togethercomputer/LLaMA-2-7B-32K which is ft with llama2 7B and support longer context length.

**Comment by olafgeibig** [comment] 2023-10-24 08:42
Duplicate of https://github.com/jmorganca/ollama/issues/877 
Has been fixed in 0.1.4

**Closed** 2023-10-24 14:29 UTC
