### ISSUE TITLE
`/api/generate` with fixed seed and temperature=0 doesn't produce deterministic results

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#586] opened 2023-09-25 02:08 UTC

**Comment by sqs** [comment] 2023-09-27 02:06
I just noticed this as well.

~3 weeks ago, the following command was deterministic:

```
curl -d '{"prompt":"const primes=[1,2,3,","model":"codellama:7b-code","options":{"seed":1337,"temperature":0,"num_ctx":100,"stop":["\n"]}}' http://localhost:11434/api/generate
```

Now it is not.

**Comment by BruceMacD** [comment] 2023-10-02 19:02
Fixed in #663

**Closed by BruceMacD** 2023-10-02 19:02 UTC
Labels: bug

**Comment by j2l** [comment] 2024-05-23 13:48
It happens again.

**Comment by d-kleine** [comment] 2024-06-06 14:02
Yeah, I can confirm this too, setting a seed and temperature=0 not leading to reproducible results

**Comment by d-kleine** [comment] 2024-06-26 19:06
I just resolved my issue with the [Ollama API docs](https://github.com/ollama/ollama/blob/main/docs/api.md#chat-request-reproducible-outputs). The [model parameters](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values) to make the model deterministic (and herewith reproducible) need to be passed in with an `"options"` key in the json input for Ollama:
```python
"options": {  
            "seed": 42, # fixed seed for determinism
            "temperature": 0, # temp set to zero for determinism
            "num_ctx": 2048 # must be set for reproducibility
        }
```

It seems like `"num_ctx"` is not fixed to a `(Default: 2048)` tokens, so that the LLM will generate slightly random output. Therefore, for **deterministic and reproducible** output, you need to set it to an appropriate fixed number of tokens for the context length supported by the LLM.

**Comment by j2l** [comment] 2024-06-27 05:40
Hey @d-kleine, do you mean you just tested it and it absolutely works for you?

Because as you can see in the message from Sep 27, 2023, we all use seed + temperature + num_ctx in options:
> `"options":{"seed":1337,"temperature":0,"num_ctx":100 ...`

**Comment by d-kleine** [comment] 2024-06-27 05:52
Yes, the output is deterministic and reproducible - on the same device with the same OS (in my case, Windows 10). However, if you have an different OS (I have tested it with Docker running an Ubuntu image on the same device), it will generate a similar but not identical output. So, the output is **deterministic** and **reproducible** on the same OS, but currently I have the issue to produce **consistent** output across different OS.

**Comment by j2l** [comment] 2024-06-27 05:55
Ok, thank you @d-kleine !
I use it on docker on my ubuntu host, maybe that's why.

**Comment by d-kleine** [comment] 2024-06-27 06:13
> I use it on docker on my ubuntu host, maybe that's why.
What OS do you use in your Docker image (not Ubuntu too, I assume)? 

What I wanted to say is that when you switch your OS running the same code, you will get a slightly differently generated output, it's inconsistent across different OS.

**Comment by d-kleine** [comment] 2024-06-27 20:20
It seems like even with the same model params (same prompt, same model, same options like a fixed `seed` and `temperature` set to 0), the firstly generated output seems to differ from the ones after that (the secondly generated output will be consistent with all following generated outputs).

**Comment by Nayar** [comment] 2024-09-09 20:04
```data = {
            "model": model,
            "raw": False,
            "options" : {
                "num_ctx" : 1024*8,
                "temperature" : 0,
                "seed": 42
            },
            "prompt" : prompt_template % (in_params['context']['products'],prompt),
            "stream" : False
}```

I am getting different results on MacOS (M3 Max 30GPU) and Linux (NVIDIA 4070 TI Super). Why is that so?

Both have same version:

`ollama version is 0.3.9`

**Comment by d-kleine** [comment] 2024-09-09 20:16
@Nayar Due to the model's architecture. So try a different model (e.g. gemma2 worked good for me across different OS) or wait for PRs to be merged:
#4632 
https://github.com/ggerganov/llama.cpp/issues/8353

**Comment by jtyska** [comment] 2024-11-13 15:02
Hey everyone, I have the opposite problem. With temperature 0, the generated content is exactly the same even if the seed is set differently. Model: qwen2.5:72b using options:{"seed":42 or 43 or 44 (always same response), temperature:0}. Does someone have this problem? Any clue on how to fix it?

**Comment by d-kleine** [comment] 2024-11-13 15:09
@jtyska Because seed and temp=0 is for making the output reproducible. If you want to generate a variable output each time you execute the generation process, don't use any seed and increase temperature to temp >0 and <=2. You could try 0.3 or 0.7 first to see if this fits your requirements.

**Comment by jtyska** [comment] 2024-11-13 15:21
Thanks for your reply @d-kleine. 

I want it to be reproducible per seed value (this is usually how random seeds work, right?). In other words, for the same seed, I want the model to generate the same response, but for different seeds, different responses.

**Comment by d-kleine** [comment] 2024-11-26 10:52
> I thought that `num_ctx` is fixed as default value (=2048) even without explicitly setting this value as 2048.

Sorry, I just have revised my statement from above. You are right, every language model has a fixed predefined context length, depending the model itself (I always look it up for each model on HF). So, no, the `num_ctx` does not change in every single execution when you use the same model (unless explicitly modified by the user or system).

**Comment by d-kleine** [comment] 2024-11-26 14:14
So the idea of setting temp=0 is making a language model deterministic, that means it always picks the highest-probability token, ensuring the output is always the same for a given input, regardless of the seed (but it can vary across hardware differences, floating-point precision errors, and multithreading, see linked issues above)

About `num_ctx`, you don't have to set this up too - a the max predefined context length is provided by the model. Sometimes it's helpful to reduce resources and inference time when shorten it. But if a part of your prompt is cut off due to a short `num_ctx`, the model's understanding of the task or context changes, leading to variations in output, even if other parameters like temperature are fixed to zero. Therefore you always have to ensure that `num_ctx` is large enough to fit your entire prompt without truncation.

**Comment by jhpjhp1118** [comment] 2024-11-27 05:33
I don't understand this comment yet.
> But if a part of your prompt is cut off due to a short num_ctx, the model's understanding of the task or context changes, leading to variations in output, even if other parameters like temperature are fixed to zero. 

After fixing the `temperature` to 0 and proceeding with the experiment further, it is deterministic when `num_ctx` is longer than prompt length, but vice versa, the response was a little inconsistent.
Even if `num_ctx` is shorter than prompt length, I was thinking that if the truncation method was consistent, the response would be consistent because I expected the truncated input to be consistent. In fact, even if `num_ctx` is shorter than prompt length, most of the responses are consistent, but sometimes there are inconsistent cases.(below 10% possibility) Why is this happening?

**Comment by d-kleine** [comment] 2024-11-27 12:00
Please provide a sample code, especially with the input, settings and the model are you using.

> After fixing the `temperature` to 0 and proceeding with the experiment further, it is deterministic when `num_ctx` is longer than prompt length, but vice versa, the response was a little inconsistent.

So, first of all, remember that most language models use subword tokenization techniques. You can test this out for example [here for the tokenizers OpenAI uses for that models](https://platform.openai.com/tokenizer) for your input, but there are more other tokenizers, each working differently. Therefore, you need to check which tokenizer your model uses if you want to reduce the context length. **And please remember: `num_ctx` is tokenized input + tokenized output**, not the tokenized input only!

About your question to the inconsistency of the output despite `temperature` set to 0: This can happen to due to a lot of reasons, for example that the value is truly very small close to zero (to avoid zero division), sampling techniques, etc. Therefore it's important to know the model are you using and it's underlying architecture and techniques used in it.

To your questions:
> Why is this happening?

That means that if important parts from your input being cut-off, the model might receive incomplete context and therefore can produce inconsistent output. Reasons for that - even with temperature 0, while the model deterministically selects the highest-probability token - can be ties in token probabilities, training biases, and positional sensitivity (e.g., primacy/recency effects), etc.

**Comment by d-kleine** [comment] 2024-11-28 10:01
My two cents on that:
* `num_ctx` is way too short, maybe increase it to 8192 (LLama 3 original context length) or something like that if you want generate at least somewhat meaningful output for your input. LLama 3.1 8b supports 128k (actually ~131k) tokens.
* I don't have deep knowledge with Kubernetes, but afaik a pod is like an instance. So, when restarting/changing the pod, the pod probably has a different state or cache, as long you don't run them with the same state (see https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/). So, yes, this can the root of why your output varies.

**Comment by hissain** [comment] 2024-12-04 10:58
Worked for me,

```
import json
import requests

ollama_url_gen = "http://localhost:11434/api/generate"
ollama_model_name = "llama3.2:latest"

torch.manual_seed(42)
np.random.seed(42)

def generate_answer(question, model=ollama_model_name):
    options = {"temperature": 0.0, "num_ctx": 4028}
    payload = {"model": model, "prompt": question, "options":options, "stream": False}
    headers = {"Content-Type": "application/json"}
    response = requests.post(ollama_url_gen, headers=headers, data=json.dumps(payload))
    
    if response.status_code != 200:
        raise Exception(f"Error from Ollama: {response.text}")
    
    return response.json().get("response", "")
```

**Comment by jtyska** [comment] 2025-01-06 16:38
I'm back here. I'm still getting some non-expected results with the temperature parameter. Please take a look at these 10 calls to API/generate with the exact same prompt, temperature=0, and varying seeds (which shouldn't do anything since the output should be deterministic, right?).  The first part is the counter of the responses, and the second is the exact payload and received responses. If you do parallel requests with varying temperatures (10 seeds for each), for instance,temperature=0 and temperature=10, this problem worsens, and temperature 0 generates several different responses to the same prompt. Could you test that and see if you can reproduce it? I suspect it is a real bug.

**Response counter for Temperature 0 (same model, same prompt, different seeds)**

{ "Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist with tasks such as writing essays, generating creative ideas, or even helping you learn new languages. Just let me know what you need assistance with!": **1**,
 "Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.\n\nIf you need any specific assistance, feel free to ask!":  **9**}

**payload/response details for each seed --- first response is different from the others)**

Starting tests with temperature: 0...
##### Seed 0 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 0,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist with tasks such as writing essays, generating creative ideas, or even helping you learn new languages. Just let me know what you need assistance with!
###### ############ ########
##### Seed 1 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 1,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 2 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 2,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 3 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 3,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 4 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 4,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 5 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 5,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 6 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 6,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 7 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 7,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 8 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 8,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########
Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
##### Seed 9 #####
###### PAYLOAD SENT to api/generate ########
{
    "model": "qwen2.5:1.5b",
    "stop": "<|endoftext|>",
    "prompt": "Hi! How are you? I am testing the impact of different temperatures in the response generated by you, could you please generate any answer you with for this request?",
    "options": {
        "seed": 9,
        "temperature": 0
    },
    "stream": false
}
###### RESPONSE GOT ########

Hello! I'm just an AI language model and don't have feelings or emotions like humans do. However, I can help you find information on a wide range of topics and assist you with tasks such as writing essays, creating presentations, answering questions about science, history, literature, etc.

If you need any specific assistance, feel free to ask!
###### ############ ########
...done with temperature: 0.

--
**Response counter for parallel requests temperature=0 and temperature=10**
Temperature = 0 - Count number by unique response
[
    7,
    2,
    1
]
Temperature = 10 - Count number by unique response
[
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
]
--
**Response counter for parallel requests of 8 different temperatures**
Temperature = 0 - Count number by unique response
[
    4,
    1,
    1,
    1,
    2,
    1
]
*all other temperatures generated 10 different responses

**Comment by jessegross** [comment] 2025-01-06 19:04
Yes, there is known non-determinism as a result of prompt caching (which affects the first response) and parallelism. It's because floating point does not give exactly the same results for different combinations of operations that are mathematically equal. The effect is more pronounced on some hardware - for example, Nvidia GPUs show it more than Apple.

**Comment by jtyska** [comment] 2025-01-06 20:03
Actually, the parallelism is on the processes that are doing the API requests. Ollama server is answering them sequentially. Each time I run multiple API requests to the same model with different seeds/temperature (0 and some other value), I get completely random responses to temperature 0. This isn't supposed to happen, right?

About the prompt caching, is it possible to disable it?

**Comment by d-kleine** [comment] 2025-01-07 00:28
> About the prompt caching, is it possible to disable it?

Not yet, see #5760 

I think it would also be good to have these settings mentioned here: https://github.com/ggerganov/llama.cpp/issues/8353
These would make generated outputs truly deterministic

**Comment by d-kleine** [comment] 2025-01-07 13:48
@jtyska I just have seen this discussion here: https://github.com/ggerganov/llama.cpp/discussions/3005#discussioncomment-11151329

Have you tried this?

**Comment by d-kleine** [comment] 2025-01-14 10:53
@jtyska Did this resolve your issue or do you need further help with this?

**Comment by jtyska** [comment] 2025-01-14 11:41
Hey @d-kleine, I'm running multiple experiments with temperature/seed values and different models, but I'm not confident that the behavior is consistent. I'm waiting for my experiments to finish, and then I will analyze their outputs to check if they are consistent or not. The workaround that I'm trying to avoid prompt-caching and any other parallel interference is not making the same model to answer multiple parallel requests. Also, when a specific experiment with seed/temperature ends, I unload the model (keep_alive=0) and load it again with the new parameters. Let's see.

I will also try to figure out how to use the top_k within the API when I have time. I let you how it goes.

**Comment by Professor-Puddle** [comment] 2025-01-30 11:13
Hi there, I might be a bit late to this, but I too have done some experiments with a couple models. (llama3.2:1b, gemma:2b for example)

# Some Info:

Disclaimer: I am very new to this stuff, so I might be wrong about some information

I've only tested this on windows 11, but as others point out, outputs may probably vary depending on different operating systems too (and maybe this might also vary depending on GPUs? I have an NVIDIA one)

 I only set the `seed` to a value. I don't set the `temperature`, `top_p`, or `top_k`. Setting those three to `0` will make the seed redundant, as I've noticed it will always produce the same output regardless of seed, and that is not what I want. I want to generate different responses, but be able to reproduce exact responses by setting a seed, and reusing the exact prompt. So yeah, I just leave the rest to default values.

# Solutions that Work for Me:
## 1. Set `keep_alive` to 0
Here's what that would look like:
```py
output = ollama.generate(
   # model, prompt, options, etc. etc. here
   keep_alive = 0
)
```
What this does:
As others have pointed out, this basically unloads the model from memory after the response is generated. You can confirm this by running a generation, and then doing `ollama ps` in the terminal. If you dont see any models there, then that means it's been unloaded (once a prompt is generated, a model will typically continue to remain loaded for 5 minutes by default)

Pros:
I've noticed that this doesn't produce any inconsistencies for me with a set seed.

Cons:
This is extremely inefficient if you want to generate multiple outputs, imagine loading and unloading an entire model for a single prompt 😭🙏

## 2. Just Generate Your Response Twice lol:
Here's what that would look like:
```py
def generate_response(model, prompt, seed = 0):
    output = None

    for _ in range(2):
        output = ollama.generate(
            model=model,
            prompt=prompt,
            options={
                "seed": seed,
            },
        )

    print(output.response)
```
Pros:
I've noticed that this fixes the prompt caching issue cos the first response is, well, ignored. It's generated, but it's ignored 🙏 
This is also much faster than unloading and reloading the model so its a no-brainer for me.

Cons:
While much faster than solution 1, this is still inefficient, especially if you have a large prompt, but it should be fine for small prompts.

Hope this helps, let me know if this works for you guys in other operating systems 😇

**Comment by huynhducloi00** [comment] 2025-02-14 02:24
this is a pretty bad issue. it basically means the platform answer differently for the same prompt. Imagine that this is used in a yes/no setup. an answer of 'yes' is 180 degree difference from no.

Without this being fixed. i don't see how Ollama can be used.

**Comment by d-kleine** [comment] 2025-02-14 12:22
> I don't set the `temperature`, `top_p`, or `top_k`. Setting those three to `0` will make the seed redundant
 
That's not true - the seed still influences the initial probability distribution affecting the model's token selection process, even for a `top_p` (limiting the cumulative probability distribution) near 0 or a low `top_k` (restricting the number of candidate tokens). Also, setting those parameters to 0 (except  `temperature`, but even then this will be close to 0) doesn't make sense imho.

**Comment by Professor-Puddle** [comment] 2025-02-14 12:29
> > I don't set the `temperature`, `top_p`, or `top_k`. Setting those three to `0` will make the seed redundant
> 
> That's not true - the seed still influences the initial probability distribution affecting the model's token selection process, even for a `top_p` (limiting the cumulative probability distribution) near 0 or a low `top_k` (restricting the number of candidate tokens). Also, setting those parameters to 0 (except `temperature`, but even then this will be close to 0) doesn't make sense imho.

Oh okay, I see, thank you for the correction 🙏

**Comment by d-kleine** [comment] 2025-02-14 13:10
No problem - just to be precise, setting `top_p` to zero is technically fine when temperature is zero since this overrides the nucleus sampling anyway (adjust either `temperature` or `top_p`, but not both simultaneously). But `top_k` must remain ≥1 to allow token selection.

**Comment by huynhducloi00** [comment] 2025-02-14 16:52
The issue still happens with top_k=1, seed=42, temperature=0, top_p (default, don't know). It does not make any sense. i ask it the same prompt. first time gives answer 'yes', second time gives answer 'no'. So, should i report this answer as yes or no in the paper. lol. This is really no use.

**Comment by d-kleine** [comment] 2025-02-14 17:09
@huynhducloi00 Please provide the model (and code, if possible)

**Comment by huynhducloi00** [comment] 2025-02-14 18:28
it can be reproduced with model 'deepseek-r1:14b'

from ollama import generate
MODEL='deepseek-r1:14b'
def get_ollama_order_flaky(prompt):
    response = generate(MODEL, prompt,options={'temperature': 0, 'seed':42, 'top_k':1})
    return response['response']

prompt="""
Here is an implementation of a method:
    package tk.mybatis.mapper.annotation;

import org.apache.ibatis.mapping.ResultFlag;
import org.apache.ibatis.mapping.ResultMap;
import org.apache.ibatis.session.Configuration;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import tk.mybatis.mapper.code.Style;
import tk.mybatis.mapper.entity.Config;
import tk.mybatis.mapper.entity.EntityColumn;
import tk.mybatis.mapper.entity.EntityTable;
import tk.mybatis.mapper.mapperhelper.EntityHelper;
import tk.mybatis.mapper.mapperhelper.SqlHelper;

import javax.persistence.Id;
import java.util.Set;

[/](https://vscode-remote+tunnel-002bcse-002dgpu2.vscode-resource.vscode-cdn.net/)**
 * @author liuzh
 */
public class IdTest {

    private Config config;

    private Configuration configuration;

    @Before
    public void beforeTest(){
        config = new Config();
        config.setStyle(Style.normal);

        configuration = new Configuration();
    }

    class UserSingleId {
        @Id
        private String name;
    }

    @Test
    public void testSingleId(){
        EntityHelper.initEntityNameMap(UserSingleId.class, config);
        EntityTable entityTable = EntityHelper.getEntityTable(UserSingleId.class);
        Assert.assertNotNull(entityTable);

        Set<EntityColumn> columns = entityTable.getEntityClassColumns();
        Assert.assertEquals(1, columns.size());

        for (EntityColumn column : columns) {
            Assert.assertTrue(column.isId());
        }

        ResultMap resultMap = entityTable.getResultMap(configuration);
        Assert.assertEquals(1, resultMap.getResultMappings().size());
        Assert.assertTrue(resultMap.getResultMappings().get(0).getFlags().contains(ResultFlag.ID));

        Assert.assertEquals("<where> AND name = #{name}</where>", SqlHelper.wherePKColumns(UserSingleId.class));
    }

    class UserCompositeKeys  {
        @Id
        private String name;

        @Id
        private String orgId;
    }

    @Test
    public void testCompositeKeys(){
        EntityHelper.initEntityNameMap(UserCompositeKeys.class, config);
        EntityTable entityTable = EntityHelper.getEntityTable(UserCompositeKeys.class);
        Assert.assertNotNull(entityTable);

        Set<EntityColumn> columns = entityTable.getEntityClassColumns();
        Assert.assertEquals(2, columns.size());
        Assert.assertEquals(2, entityTable.getEntityClassPKColumns().size());

        for (EntityColumn column : columns) {
            Assert.assertTrue(column.isId());
        }

        ResultMap resultMap = entityTable.getResultMap(configuration);
        Assert.assertEquals(2, resultMap.getResultMappings().size());
        Assert.assertTrue(resultMap.getResultMappings().get(0).getFlags().contains(ResultFlag.ID));
        Assert.assertTrue(resultMap.getResultMappings().get(1).getFlags().contains(ResultFlag.ID));

        Assert.assertEquals("<where> AND name = #{name} AND orgId = #{orgId}</where>", SqlHelper.wherePKColumns(UserCompositeKeys.class));
    }

}


    can `testCompositeKeys` be flaky depending on the order of which it is run compared to other tests. Yes or No only.
"""

It sometimes give answer yes, sometimes no, especially when you flip a different prompt in between.

**Comment by d-kleine** [comment] 2025-02-14 19:39
@huynhducloi00 Pleas try with `options={"temperature": 0, "seed": 42, "top_k": 1, "top_p": 1}`, at least on my end (GPU) it's reproducible consistently across multiple runs; Please let me know if that suits your requirements

**Comment by huynhducloi00** [comment] 2025-02-14 23:09
Thanks a lot for the response. That option "top_p" seem NOT available for the client API?

response = client.chat(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt,
            },
        ],
        options={"temperature": 0, "seed": 42, "top_k": 1, 'num_ctx':10000, "top_p":1},
    )

This will complains about "top_p" not recognized

**Comment by huynhducloi00** [comment] 2025-02-15 21:54
sadly, "top_p" does not solve it:
Here is the result of 10 questions:
```
Run 1:
[(5, False),
 (6, True),
 (7, False),
 (8, True),
 (9, True),
 (10, True),
 (11, True),
 (12, True),
 (13, False),
 (14, False)]

Run 2:
[(5, False),
 (6, True),
 (7, True),
 (8, True),
 (9, False),
 (10, True),
 (11, True),
 (12, True),
 (13, False),
 (14, True)]
```

They are off (different) at index 7. 
* here is the answer at run 1: https://justpaste.it/dc73s
* Here is the answer at run 2: https://justpaste.it/3t6y9

model being test is deepseek-r1:14b. The option is `"temperature": 0, "seed": 42, "top_k": 1, 'top_p':1,'num_ctx':10000`


I am not sure why this is not being prioritized. This is very easy to reproduce. Is it due to the randomness in the quantization. I guess deepseek-r1:14b is a quantized model.

**Comment by d-kleine** [comment] 2025-02-16 01:23
Have you tried without limiting the context length (`num_ctx')?

There can be another numerous reasons that can introduce randomness, e.g.
 - PRNG initialization between runs
 - parallel GPU computation (nothing can be done about this; you can double-check if this behaviour is the same on CPU only too)
 - quantization method (Q4_K_M)
 - floating point arithmetic (fp32, fp16, bfloat16)
 - etc. pp.

**Comment by dan31** [comment] 2025-03-26 01:03
Wow this is disastrous. We encounter this a lot now. What is the true reason quantized models cannot produce deterministic outputs when all non-determinism is off in ollama? This is a completely serial execution on GPU by a single client for us with a Q4_K_M model, the most popular quantization format.

**Comment by kevin-pw** [comment] 2025-03-26 19:10
> model being test is deepseek-r1:14b. The option is `"temperature": 0, "seed": 42, "top_k": 1, 'top_p':1,'num_ctx':10000`

I wrote a longer comment in the related (and still open) issue here: https://github.com/ollama/ollama/issues/5321#issuecomment-2755465128 but the main takeaway is: Several models also produce inconsistent embeddings for the same inputs, which can significantly affect quality of downstream applications, for example RAG. That also means sampler options (like `temperature`, `seed`, `top_k`, etc.) cannot fix this issue.

**Comment by flexorx** [comment] 2025-03-26 22:26
@kevin-pw do you know if this issue is recently introduced?
I couldn't find any mentions of a similar issue until recently.

**Comment by huynhducloi00** [comment] 2025-05-09 22:31
yes, not sure why the team does not prioritize this
