### ISSUE TITLE
ollama push username/UppercaseModelname fails with 401 error

### ISSUE THREAD

**Issue by easp** [jmorganca/ollama#947] opened 2023-10-29 19:21 UTC
I tried pushing a model I'd created with capital letters in the name and repeatedly got a 401 error. It took me a while to figure out why.

It seems like the error should be more descriptive and/or `ollama create` and `ollama cp` should enforce the lower-case only rule.

**Comment by technovangelist** [comment] 2023-10-29 19:35
Hey there. Thanks for the issue but looks like a duplicate of #927

**Closed** 2023-10-29 19:35 UTC

**Comment by easp** [comment] 2023-10-29 19:43
@technovangelist It's related, but different. 

That's just about the error due to lack of the username. This is about handling of upper-case model names during push, and in general.

**Comment by technovangelist** [comment] 2023-10-30 00:54
sorry, that one pointed to another issue that was about the uppercase which got close because it was a duplicate of yet another issue about uppercase.... #336

**Comment by technovangelist** [comment] 2023-10-30 00:55
I have been burned by this one as well, and when someone else experienced it last week I was eager to get it in there. Thanks again for submitting and for all of your help in the Discord.
