### ISSUE TITLE
Support multi-modal models

### ISSUE THREAD

**Issue by arian81** [jmorganca/ollama#746] opened 2023-10-10 01:14 UTC
This is one of the best open source multi modals based on llama 7 currently. It would nice to be able to host it in ollama. 
https://llava-vl.github.io/

**Comment by ryansereno** [comment] 2023-10-10 17:47
Came here looking for this, to see if the discussion had begin surrounding this.
Curious to see what will be required to make this happen.

**Comment by marscod** [comment] 2023-10-15 22:15
I could successfully run `llava-v1.5-7b` and it is available at: https://ollama.ai/marscod/llava but I have to map an `image` parameter to `lama.cpp`'s image parameter. Maybe within the prompt?

**Comment by chigkim** [comment] 2023-10-16 03:11
File reader command in the prompt like /read file.jpg?

**Comment by hugh-min** [comment] 2023-10-17 07:52
> I could successfully run `llava-v1.5-7b` and it is available at: https://ollama.ai/marscod/llava but I have to map an `image` parameter to `llama.cpp`'s image parameter. Maybe within the prompt?

Could you elaborate on how to map an image within ollama?

**Comment by navyfighter12** [comment] 2023-10-28 18:40
> > I could successfully run `llava-v1.5-7b` and it is available at: https://ollama.ai/marscod/llava but I have to map an `image` parameter to `llama.cpp`'s image parameter. Maybe within the prompt?
> 
> Could you elaborate on how to map an image within ollama?

I would like to know as well. Thanks

**Comment by tmc** [comment] 2023-10-29 07:02
it seems a couple of interface design decisions are are play: 1) how to represent this in the http api and 2) what the user/cli interface should be.

I want to note/highlight that the folks hacking on iTerm2 have done some work that may be relevant in the cli context here: https://iterm2.com/documentation-images.html

For the HTTP interface I'd suggest taking some inspiration of how OpenAI is folding in image may be useful. I did a bit of protocol decoding and the TL;DR of how they do it is upload to blob store then include a special message type in the completion message list.

There's also a/the consideration of if it's an ollama concern to allow annotation of an incoming image to support highlighting part of the image. That feels a bit out of scope to start but perhaps the design should keep that in mind.

**Comment by sausheong** [comment] 2023-11-03 14:44
> > > I could successfully run `llava-v1.5-7b` and it is available at: https://ollama.ai/marscod/llava but I have to map an `image` parameter to `llama.cpp`'s image parameter. Maybe within the prompt?
> > 
> > 
> > Could you elaborate on how to map an image within ollama?
> 
> I would like to know as well. Thanks

Me too, can explain how to map an image within ollama?

**Comment by itsPreto** [comment] 2023-11-11 01:43
Love that this is marked as closed but everyone still clueless over here lol

**Comment by orkutmuratyilmaz** [comment] 2023-11-18 17:29
@marscod thanks for importing the model. Can you type an example of API call, on [the model page](https://ollama.ai/marscod/llava)?

**Comment by ryansereno** [comment] 2023-11-21 12:18
@mangiucugna thank you, will give it a try.
Hadn't heard of Bakllava before, very excited to try it.

**Comment by mangiucugna** [comment] 2023-11-21 17:37
I imported bakllava-1 locally and did some tests and it performs so badly when compared to the llama.cpp implementation that is unusable.
I suspect that something is going wrong and the data arriving to the model is corrupted and that somehow `{"error":"error reading llm response: bufio.Scanner: token too long"}` is related.

Happy to share my Modelfile and link to the gguf for anyone to try to reproduce

**Comment by mak448a** [comment] 2023-12-15 02:05
Since this is now added, I can't figure out how to upload an image to the model. When I follow the instructions at: https://github.com/jmorganca/ollama/releases/tag/v0.1.15, it describes something completely different than what was in the picture. I'm on Linux.

**Comment by arian81** [comment] 2023-12-15 03:00
> Since this is now added, I can't figure out how to upload an image to the model. When I follow the instructions at: https://github.com/jmorganca/ollama/releases/tag/v0.1.15, it describes something completely different than what was in the picture. I'm on Linux.

You probably haven't updated to the latest version of Ollama if you're getting a bunch of Chinese characters as the output.

**Comment by orkutmuratyilmaz** [comment] 2023-12-16 07:18
I guess that we can consider this issue as completed :)

**Closed** 2023-12-16 09:00 UTC
Labels: enhancement

**Comment by prologic** [comment] 2023-12-26 04:34
When I try this I get:

```
$ ollama run llama2
>>> What's in this image? /Users/prologic/Downloads/IMG_1325.png

I cannot directly view or analyze the image you provided as it is a personal file located on a local computer. However, I can provide some general
information about images and how they can be analyzed.
...
```

And I'm using the l atest version of ollama:

```
$ ollama --version
ollama version is 0.1.17
```

**Comment by pdevine** [comment] 2023-12-26 06:20
@prologic llama2 isn't a multimodal model. You should try:
```
$ ollama run llava
```

**Comment by prologic** [comment] 2023-12-26 06:32
Ahh! Thanks. When I tried to search for [multimodel models](https://ollama.ai/library?q=multimodal) the search turend up empty. This is why I wasn't able to figure this out so easily :/ There should be a way to list for and search for multimodel models, even with `ollama search` (does this sub-command exist?)

**Comment by schuster-rainer** [comment] 2024-03-06 13:12
if you want to use it with langchain. here is what you need to add to the HumanMessage:

```python
 HumanMessage(
                content=[
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": f"data:image/jpeg;base64,{img_base64}",
                    },
                ]
            )
```
