### ISSUE TITLE
Out of nowhere when I run my script I get this error randomically: raise ValueError("No data received from Ollama stream.")

### ISSUE THREAD

**Issue by alelagamba** [jmorganca/ollama#1329] opened 2023-11-30 12:33 UTC
Traceback (most recent call last):
  File "/Users//Desktop/python-test/display_attribute.py", line 34, in <module>
    answer = llm("Given this text:" + str(first_column_value) + "Does it talk about a display or screen of the product? Answer only 'Yes' or 'No'.")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//Desktop/python-test/.venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 879, in __call__
    self.generate(
  File "/Users//Desktop/python-test/.venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 656, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//Desktop/python-test/.venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 543, in _generate_helper
    raise e
  File "/Users//Desktop/python-test/.venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 530, in _generate_helper
    self._generate(
  File "/Users//Desktop/python-test/.venv/lib/python3.11/site-packages/langchain/llms/ollama.py", line 241, in _generate
    final_chunk = super()._stream_with_aggregation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//Desktop/python-test/.venv/lib/python3.11/site-packages/langchain/llms/ollama.py", line 190, in _stream_with_aggregation
    raise ValueError("No data received from Ollama stream.")
ValueError: No data received from Ollama stream.
(.venv) sh-3.2$ 

I really have no clue because previously it all worked really fine. It's just a simple script that takes a string from a csv and puts it inside the question for the LLM like so:
answer = llm("Given this text:" + str(first_column_value) + "Does it talk about a display or screen of the product? Answer only 'Yes' or 'No'.")

**Comment by Govind-S-B** [comment] 2023-12-02 15:06
Same issue here, my thing was working fine last week but now it just breaks , not sure why its breaking either. Related issue : https://github.com/whitead/paper-qa/issues/213

**Comment by BruceMacD** [comment] 2023-12-04 23:13
This seems like it could be an error in Langchain. Maybe from an older version. Is anyone able to reproduce using one of our examples?
https://github.com/jmorganca/ollama/tree/main/examples/langchain-python-simple

**Comment by alelagamba** [comment] 2023-12-05 15:33
> Yeah it seems to be working fine with the hello world application , I wonder what went wrong with my code , will look into it later.
> 
> But here is the result for the example : ![image](https://private-user-images.githubusercontent.com/62943847/288089552-68cb0e51-7a7d-4238-9bd1-9835f2585f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTA1NTcsIm5iZiI6MTcwMTc5MDI1NywicGF0aCI6Ii82Mjk0Mzg0Ny8yODgwODk1NTItNjhjYjBlNTEtN2E3ZC00MjM4LTliZDEtOTgzNWYyNTg1ZjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE1MzA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NTE0NDUyMDVjNjAwYTczMDNmZTI1OWE5YjdiYjEzODZjOTllNWY5ZTgyNmQyMDA5ZGY0OGJhOGIwMTA2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OndAT0JEcul6jFmBxooRLCn3h8fIy85c5Ku2NfrEe1Q)

The thing is that also for my code it runs pretty well usually, but sometimes out of nowhere it shows me the error I wrote in the original post. Don't actually know what to do, for sure the only thing that partially solves the problem is that when I use the Run&Debug mode it tends to bring the error much later than when I run it normally.

**Comment by BruceMacD** [comment] 2023-12-05 23:09
Any idea which version of langchain's python library you are seeing this on?

**Comment by dennis-thevara** [comment] 2023-12-07 14:33
So I've been having this issue as well, and it's quite strange, because like OP I've been able to run things fine last week. I was trying to run the Private Multi-Modal RAG Cookbook in the Langchain repo.

For what it's worth, when I ran it, Ollama is indeed streaming a sequence of tokens. I've verified this with the `StreamingStdOutCallbackHandler`. What I've noticed is the aforementioned error only hits at the very end of the streaming response, once the model has concluded its output. 

By the traceback, in `ollama.py`, `_stream_with_aggregation` raises the error when the final chunk it gets from Ollama is `None`. Out of curiosity I changed this to set the final chunk to a `GenerationChunk` object with the `text` attribute set to an empty string. My assumption was that the final token from Ollama would be a nonetype when it's done, so instead of raising an error, I had it return an analogue to an end-of-text object. This appears to fix the issue for my specific use case, but I highly doubt this is sensible for general use. I haven't looked into whether it will break anything else. I just figured I'd chime in, in case it provides a clue about what's causing the issue.

For reference, I am using `langchain==0.0.344` and this is the change I made in `_stream_with_aggregation`:
```python
if final_chunk is None:
    final_chunk = GenerationChunk(text="")
    # raise ValueError("No data received from Ollama stream.")
```

**Comment by kennethwork101** [comment] 2023-12-10 19:32
Installed ollama version is 0.1.14 and is working now. 
ollama version 0.1.13 was failing.
No change to langchain Version: 0.0.340

**Comment by dennis-thevara** [comment] 2023-12-11 09:37
Can confirm that updating ollama fixed it for me too. Mine was 0.1.12 before update.

**Comment by BruceMacD** [comment] 2023-12-11 22:40
Thanks for letting us know this is working now. I suspect this was a concurrent request bug that I fixed in the last release. Resolving this now.

**Closed by BruceMacD** 2023-12-11 22:40 UTC

**Comment by kwong99** [comment] 2023-12-12 00:00
Hi,
Thanks for fixing the issue.
Is there a way to install a previous version of ollama?
I am hoping to run a previous version if the current version is having
issues.
Thanks.
kenneth

**Comment by BruceMacD** [comment] 2023-12-12 15:44
@kwong99 if you're seeing the error in this issue using the most recent version will most likely fix the issue, otherwise you can download old versions from here:
https://github.com/jmorganca/ollama/releases
