### ISSUE TITLE
Can't build custom models

### ISSUE THREAD

**Issue by selfagency** [jmorganca/ollama#489] opened 2023-09-07 22:17 UTC
I'm trying to build a custom model from a model I have already successfully pulled and used locally, but no matter what I do, it throws an error:

```Modelfile
FROM codellama:latest
SYSTEM """

You are an expert in Nushell.
"""
```

```sh
❯ ollama list
NAME            	ID          	SIZE  	MODIFIED       
codellama:latest	36893bf9bc7f	3.8 GB	10 minutes ago	
llama2:13b      	984c614c4037	7.3 GB	24 minutes ago	
llama2:latest   	5c1a4ea68dd0	3.8 GB	7 minutes ago

❯ ollama create nushell -f ./Modelfile
parsing modelfile    
looking for model    
creating model system layer    
creating model license layer    
looking for model    
pulling model file    
⠋ pulling manifest  Error: pull model manifest: model not found
```

I'm running v0.0.18 installed via Homebrew on MacOS Sonoma Beta.

**Comment by mxyng** [comment] 2023-09-07 23:10
@selfagency, I'm not able to reproduce this on Homebrew's v0.0.18. Using your Modelfile, this should be the expected output:

```
$ cat Modelfile
FROM codellama:latest
SYSTEM """

You are an expert in Nushell.
"""
$ ollama create nushell -f ./Modelfile
parsing modelfile
looking for model
creating model system layer
creating config layer
using already created layer sha256:8268242df6f07932d5e6ef3ea276dd61a1420f0515a5f0ecdc7f11cbbf6ddb7c
using already created layer sha256:2c8743bdc4adb945dfa32717f767ce4984302fc802fc4fb80e235c67bc2df16d
using already created layer sha256:38fa20ee7daa67cfbdb181371e784bf30b22cd0c2bb12acc5b808a24b3e569f9
using already created layer sha256:578a2e81f7064c5118b93336dbe53dff6049bbeb4a8cee6c32a87579022e1aba
using already created layer sha256:404e21afdc6a34316cb23740018284bff1d16a480db6f8f59f4d5626dfb73376
writing layer sha256:9b21bb0bfe24e59a4bbf773ef7826b60ddcd2b478fd93d3213f205d5a62b95e8
writing layer sha256:7e969f73abb05a38023b880019a68fc69894aba8402552e1aad9ce8bf9568c76
writing manifest
success
```

```
$ brew info ollama
==> ollama: stable 0.0.18 (bottled), HEAD
Create, run, and share large language models (LLMs)
https://ollama.ai/
/opt/homebrew/Cellar/ollama/0.0.18 (7 files, 15.7MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-07 at 15:57:57
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/ollama.rb
License: MIT
==> Dependencies
Build: cmake ✘, go ✘
==> Options
--HEAD
        Install HEAD version
==> Caveats
To start ollama now and restart at login:
  brew services start ollama
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/ollama/bin/ollama serve
==> Analytics
install: 521 (30 days), 600 (90 days), 600 (365 days)
install-on-request: 521 (30 days), 600 (90 days), 600 (365 days)
build-error: 9 (30 days)
```

Can you attach the server logs? If the server is started with `brew services`, logs are located in `$(brew --prefix)/var/log/ollama.log`. If you started the server manually with `ollama server`, logs will be printed to stdout.

**Comment by jmorganca** [comment] 2023-10-23 16:33
Hi there, thanks for creating an issue! Given there hasn't been much activity in the last month, I'll close this for now. Feel free to re-open it! Also, make sure to update to the latest version (0.1.3 as of this writing :-)

**Closed by jmorganca** 2023-10-23 16:33 UTC
