### ISSUE TITLE
Is there a way to install ollama and download models on a external SSD on mac M1 ?

### ISSUE THREAD

**Issue by pramitsawant** [jmorganca/ollama#1625] opened 2023-12-20 10:06 UTC
On Macbook Pro M1
The models are downloaded to this path /Users/{username}/.ollama/models/manifests/registry.ollama.ai/library

I use a external ssd where i download and keep all less recently used apps and other files.

can we have an option to set model download path ?

**Comment by mattbisme** [comment] 2023-12-20 18:11
This is a good idea. I don't seem to recall a configuration option for putting the models on another location.

**Comment by justinh-rahb** [comment] 2023-12-20 19:52
In the meantime, you could use LM Studio to download and store models elsewhere and create custom modelfiles to import them. You won't have the advantage of the ollama model download management of course, but it'll accomplish your goal.

**Comment by prantlf** [comment] 2023-12-21 11:38
You could try symlinking `~/.ollama` to your external disk.

**Comment by easp** [comment] 2023-12-22 01:59
Symlinking ~/.ollama or ~/.ollama/models is the best way to go right now. 

The ollama app will use the value of the OLLAMA_MODELS environment variable if you launch it from a shell like so`OLLAMA_MODELS=DIRPATH start /Applications/Ollama.app` , but the problem is that there is no good way to set the variable that works across restarts. You have to disable the normal Launch at Login functionality and instead set up your own launchd job.

**Comment by technovangelist** [comment] 2024-01-03 19:48
hi @pramitsawant It looks like the comment from @easp solves your issue. That is, in fact, the right way to achieve this. I'll go ahead and close this issue, but if you still have a problem, reopen, and we can continue to look at it. There is a FAQ in the Ollama docs that covers how to set environment variables on different platforms. Thanks so much for being part of this great community.

**Closed by technovangelist** 2024-01-03 19:48 UTC

**Comment by hasandenizuk** [comment] 2024-02-23 23:29
Any updates on this? I have a full C drive :D
