### ISSUE TITLE
Support openai api

### ISSUE THREAD

**Issue by thawkins** [jmorganca/ollama#1366] opened 2023-12-03 17:31 UTC
Would it be possible to add a "serveOpenAI" command that changes the REST api schema to match that of the OpenAI api. This would open up a wide range of tools that could then be connected to ollama via this API. 

Authentication could for now be ignored if provided until it felt that ollama needs that capability. 

Api could be served on a different url structure.

**Comment by phalexo** [comment] 2023-12-04 01:11
You can use litellm to wrap ollama and litellm will give you an openAI API.

**Comment by Thelouras58** [comment] 2023-12-04 12:36
@phalexo  is right. You can check https://www.youtube.com/watch?v=y7wMTwJN7rA

**Comment by technovangelist** [comment] 2023-12-04 22:01
Thanks for the issue, but it looks like it’s a duplicate of #305, plus this one mentions another workaround using litellm. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Closed by technovangelist** 2023-12-04 22:01 UTC
