### ISSUE TITLE
How to call ollama to use downloaded weights?

### ISSUE THREAD

**Issue by smuskal** [jmorganca/ollama#163] opened 2023-07-21 15:17 UTC
Meta enabled download of the models - https://github.com/facebookresearch/llama/blob/main/README.md   How can ollama be directed to use downloaded model/weights?

**Comment by pdevine** [comment] 2023-07-21 17:09
This is a dupe of #159

**Closed by pdevine** 2023-07-21 17:09 UTC

**Comment by smuskal** [comment] 2023-07-21 18:51
Thank you - I see #159 indicates a direction "need to re-quantize the weights for the model (which is a pain), and convert it to ggml v3."  Can you provide a link with a stepwise procedure?  I am sure others will benefit from it. I asked bard, but not convinced it is accurate :)

Also, once a local model is referenced, is there a way to leverage langchain against it?
