### ISSUE TITLE
Make models directory customizable

### ISSUE THREAD

**Issue by tastycode** [jmorganca/ollama#513] opened 2023-09-12 10:28 UTC
https://github.com/jmorganca/ollama/blob/45ac07cd025f9d1e84917db3f00e0f3e5651aede/server/modelpath.go#L135C7-L136C31

If you are often working with different AI packages, you know that the models add up quickly. I keep my models on an external drive. The user to at least customize this behavior with an environment variable. I am not up-to-speed on go tooling, otherwise I'd be happy to open a PR.

**Comment by justinmayer** [comment] 2023-09-23 21:30
Dupe of #153. This should be closed to prevent issue clutter.

**Comment by mchiang0610** [comment] 2023-09-30 05:04
Closing this for the duplicate issue #153 

Thanks @justinmayer and @tastycode

**Closed by mchiang0610** 2023-09-30 05:04 UTC
